/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CargaIniModel;
import model.DadosCargaInicial;
import model.ModeloTabelaAtualizacao;
import model.ModeloTabelaBloqueio;
import model.ModeloTabelaCampanha;
import model.ModeloTabelaCarga;
import model.ModeloTabelaConfiguracoes;
import model.ModeloTabelaEmail;
import model.ModeloTabelaTelefone;
import modeloConexao.ConexaoBD;

/**
 *
 * @author j
 */
public class TelaImplantacao extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    /**
     * Creates new form TelaImplantacao
     */

    CargaIniModel mo = new CargaIniModel();

    public TelaImplantacao() {
        initComponents();
        preencherTabelaTel("select * from cargainicial c where c.cod >= 8 and c.cod <=18");
        preencherTabelaCarga("select * from cargainicial c where c.cod >= 1 and c.cod <=7");
        preencherTabelaBloqueio("select * from cargainicial c where c.cod >= 19 and c.cod <=28");
        preencherTabelaEmail("select * from cargainicial c where c.cod >= 29 and c.cod <=36");
        preencherTabelaAtualizacao("select * from cargainicial c where c.cod >= 37 and c.cod <=44");
        preencherTabelaCampanha("select * from cargainicial c where c.cod >= 45 and c.cod <=57");
        preencherTabelaConfiguracoes("select * from cargainicial c where c.cod >= 58 and c.cod <=71");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltaImpl = new javax.swing.JButton();
        btnCronograma = new javax.swing.JButton();
        btnPosImpl = new javax.swing.JButton();
        btnSalvarImpl = new javax.swing.JButton();
        jtEmail = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCarga = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTelefone = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtableBloqueio = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableEMail = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableAtualiz = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableCampanha = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtConfiguracao = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAdicional = new javax.swing.JTable();
        btnAdicionaDescricao = new javax.swing.JButton();
        jtAdicionalDescricao = new javax.swing.JTextField();
        jtObservAdicional = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Implantação");
        setResizable(false);

        btnVoltaImpl.setText("Voltar tela principal");
        btnVoltaImpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltaImplActionPerformed(evt);
            }
        });

        btnCronograma.setText("Cronograma");

        btnPosImpl.setText(" Pós implantação");
        btnPosImpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosImplActionPerformed(evt);
            }
        });

        btnSalvarImpl.setText("Salvar");

        jPanel1.setLayout(null);

        jTableCarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCarga.setColumnSelectionAllowed(true);
        jTableCarga.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableCarga);
        jTableCarga.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(0, 10, 1170, 390);

        jtEmail.addTab("1.Carga Inicial", jPanel1);

        jTableTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTelefone.setColumnSelectionAllowed(true);
        jTableTelefone.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableTelefone);
        jTableTelefone.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtEmail.addTab("2.Telefonia", jPanel2);

        jtableBloqueio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtableBloqueio.setColumnSelectionAllowed(true);
        jtableBloqueio.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jtableBloqueio);
        jtableBloqueio.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtEmail.addTab("3.Bloqueio de clientes", jPanel3);

        jTableEMail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEMail.setColumnSelectionAllowed(true);
        jTableEMail.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTableEMail);
        jTableEMail.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtEmail.addTab("4.E-mail", jPanel4);

        jTableAtualiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAtualiz.setColumnSelectionAllowed(true);
        jTableAtualiz.setRowHeight(20);
        jTableAtualiz.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTableAtualiz);
        jTableAtualiz.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtEmail.addTab("5.Atualização", jPanel5);

        jTableCampanha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableCampanha.setColumnSelectionAllowed(true);
        jTableCampanha.setRowHeight(20);
        jTableCampanha.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(jTableCampanha);
        jTableCampanha.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtEmail.addTab("6.Campanha e resultado", jPanel6);

        jtConfiguracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtConfiguracao.setColumnSelectionAllowed(true);
        jtConfiguracao.setRowHeight(20);
        jtConfiguracao.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(jtConfiguracao);
        jtConfiguracao.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jtEmail.addTab("7.Configurações", jPanel7);

        jTableAdicional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Observação"
            }
        ));
        jTableAdicional.setColumnSelectionAllowed(true);
        jTableAdicional.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableAdicional);
        jTableAdicional.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnAdicionaDescricao.setText("Adicionar ações");
        btnAdicionaDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaDescricaoActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar alterações");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnAdicionaDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jtAdicionalDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtObservAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtAdicionalDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtObservAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionaDescricao)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        jtEmail.addTab("Observações e adicionais", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jtEmail.addTab("PSC-IP-000 INFORMACOES TECNICAS 1.1", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVoltaImpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCronograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPosImpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarImpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtEmail)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtEmail)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltaImpl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPosImpl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarImpl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(1348, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltaImplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltaImplActionPerformed
        TelaPrincipal tp = new TelaPrincipal();
        tp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltaImplActionPerformed

    public void preencherTabelaTel(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaTelefone modelo = new ModeloTabelaTelefone(dados, colunas);
        jTableTelefone.setModel(modelo);
        jTableTelefone.getColumnModel().getColumn(0).setPreferredWidth(900);
        jTableTelefone.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
 
    public void preencherTabelaAtualizacao(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaAtualizacao at = new ModeloTabelaAtualizacao(dados, colunas);
        jTableAtualiz.setModel(at);
        jTableAtualiz.getColumnModel().getColumn(0).setPreferredWidth(900);
        jTableAtualiz.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    
    
    public void preencherTabelaCarga(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaCarga mod = new ModeloTabelaCarga(dados, colunas);
        jTableCarga.setModel(mod);
        jTableCarga.getColumnModel().getColumn(0).setPreferredWidth(900);
        jTableCarga.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    
    public void preencherTabelaConfiguracoes(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaConfiguracoes co = new ModeloTabelaConfiguracoes(dados, colunas);
        jtConfiguracao.setModel(co);
        jtConfiguracao.getColumnModel().getColumn(0).setPreferredWidth(900);
        jtConfiguracao.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    
    public void preencherTabelaCampanha(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaCampanha ca = new ModeloTabelaCampanha(dados, colunas);
        jTableCampanha.setModel(ca);
        jTableCampanha.getColumnModel().getColumn(0).setPreferredWidth(900);
        jTableCampanha.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    
    public void preencherTabelaBloqueio(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaBloqueio mod = new ModeloTabelaBloqueio(dados, colunas);
        jtableBloqueio.setModel(mod);
        jtableBloqueio.getColumnModel().getColumn(0).setPreferredWidth(900);
        jtableBloqueio.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    

     public void preencherTabelaEmail(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Observação"};
        conex.conectar();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("descricao"), conex.rs.getString("observacao")});
            } while (conex.rs.next());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher arraylist" + e.getMessage());
        }
        conex.desconectar();
        ModeloTabelaEmail em = new ModeloTabelaEmail(dados, colunas);
        jTableEMail.setModel(em);
        jTableEMail.getColumnModel().getColumn(0).setPreferredWidth(900);
        jTableEMail.getColumnModel().getColumn(1).setPreferredWidth(350);
    }
    
    private void btnPosImplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosImplActionPerformed
        TelaPosImplantacao tpos = new TelaPosImplantacao();
        tpos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPosImplActionPerformed

    private void btnAdicionaDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaDescricaoActionPerformed

        jTableAdicional.getColumnModel().getColumn(0).setPreferredWidth(900);
        jTableAdicional.getColumnModel().getColumn(1).setPreferredWidth(350);
        
        
        String descricao = jtAdicionalDescricao.getText().trim();
        String observ = jtObservAdicional.getText().trim();
        
        if(jtAdicionalDescricao.getText().equals("") && jtObservAdicional.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pelo menos 1 campo deve conter algum dado.");
        }else{
            DefaultTableModel val = (DefaultTableModel) jTableAdicional.getModel();
            val.addRow(new String[]{descricao,observ});
        }
        jtAdicionalDescricao.setText("");jtObservAdicional.setText("");
        jtAdicionalDescricao.requestFocus();
    }//GEN-LAST:event_btnAdicionaDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImplantacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImplantacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImplantacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImplantacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImplantacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaDescricao;
    private javax.swing.JButton btnCronograma;
    private javax.swing.JButton btnPosImpl;
    private javax.swing.JButton btnSalvarImpl;
    private javax.swing.JButton btnVoltaImpl;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableAdicional;
    private javax.swing.JTable jTableAtualiz;
    private javax.swing.JTable jTableCampanha;
    private javax.swing.JTable jTableCarga;
    private javax.swing.JTable jTableEMail;
    private javax.swing.JTable jTableTelefone;
    private javax.swing.JTextField jtAdicionalDescricao;
    private javax.swing.JTable jtConfiguracao;
    private javax.swing.JTabbedPane jtEmail;
    private javax.swing.JTextField jtObservAdicional;
    private javax.swing.JTable jtableBloqueio;
    // End of variables declaration//GEN-END:variables
}
